application: quotechu
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 100ms
  max_pending_latency: 500ms
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: quotechu.application



